'use strict';
/* The four console webhooks behind Console, Ads (CONSOLE-ADS-API.md): ads-confirm, ads-budget, ads-ad-status, ads-campaign-status.
 * Pure decision logic plus one network function (applyWrite, Graph through meta-ads.js). The n8n workflow
 * automation/SUB-ads-console.json (generated by build-ads-console.mjs) only moves data between Postgres nodes and these functions,
 * loaded as require('lv-automation').adsConsole (I-46c).
 *
 * What is enforced here, server side, whatever the browser sends:
 *  - caller = a Supabase user JWT (HS256, SUPABASE_JWT_SECRET) AND public.has_role(uid, 'admin'); `confirmed_by` / `requested_by` are the JWT user.
 *  - the target must be a SortMyCover object: it is read from ad_objects joined to the brands row where code = 'SMC'. Page / account IDs
 *    come from that row (meta-ads.js smcAssets); the browser never sends one.
 *  - caps (daily, monthly = sum of active brokers' media shares / 1.15), the +20% step, 48 h spacing, Meta minimum: checked at the
 *    preview (so no token is minted for a write that would be refused) and again at apply (meta-ads.js setCampaignBudget).
 *  - go-live: `go_live` is a flag only. The share is the newest active cycle's media_share_zar read from the database; the raise may not
 *    exceed share / 1.15 / 30 and only Campaign A may use it. A `go_live_share_zar` sent by the browser is ignored.
 *  - confirm token: HMAC (META_CONFIRM_SECRET), bound to action + target + the SERVER-normalised params, 15 min, single use. Single use is
 *    enforced across runs by a row in public.ads_write_log (unique nonce, claimed BEFORE the Graph call).
 * Nothing here runs by itself: every write needs a human tap on the console (rule 5). */
const M = require('./meta-ads.js');
const LP = require('./launch-plan.js');
const LT = require('../security/lead-token.js');

const ROUTES = { confirm: 'ads-confirm', budget: 'ads-budget', 'ad-status': 'ads-ad-status', 'campaign-status': 'ads-campaign-status' };
const CONFIRM_ACTIONS = new Set(['set_campaign_budget', 'pause_ad', 'resume_ad', 'pause_campaign', 'resume_campaign']);
const ID_RE = /^[A-Za-z0-9_-]{1,64}$/;
const UUID_RE = /^[0-9a-f-]{36}$/i;

const STATUS_FOR = {
  CONFIRM_REQUIRED: 400, CONFIRM_INVALID: 400, CONFIRM_EXPIRED: 410, CONFIRM_MISMATCH: 409, CONFIRM_REUSED: 409, CONFIRM_SECRET_MISSING: 503,
  DAILY_CAP: 422, MONTHLY_CAP: 422, BUDGET_BELOW_MIN: 422, BUDGET_INVALID: 422, STEP_LIMIT: 422, STEP_COOLDOWN: 422, CAP_MISSING: 422,
  GO_LIVE_EXCEEDS_SHARE: 422, GO_LIVE_SHARE_MISSING: 422, GO_LIVE_NO_ACTIVE_CYCLE: 422, GO_LIVE_ONLY_A: 422,
  RATE_LIMIT_BACKOFF: 429, RATE_LIMIT: 429, TOO_SOON: 429, NO_TOKEN: 503, AUTH_NOT_CONFIGURED: 503, NETWORK: 502, API_ERROR: 502,
  NOT_ADMIN: 403, TARGET_NOT_FOUND: 404, BAD_TARGET: 409, BRAND_REQUIRED: 409, BRAND_NOT_SMC: 409, ASSET_MISSING: 409, NOT_SMC_PAGE: 409, NOT_SMC_ACCOUNT: 409,
  UNSUPPORTED_ACTION: 400, BAD_INPUT: 400, AUDIT_WHY: 400, AUDIT_WHO: 400,
};
const fail = (code, message, extra = {}, status) => ({ ok: false, status: status || STATUS_FOR[code] || 400, body: { ok: false, code, message, ...extra } });
const fromErr = (e) => fail(e.code || 'BAD_INPUT', e.message || String(e), e.retryAfterMs ? { retry_after_ms: e.retryAfterMs } : {});

/* ---------------------------------------------------------------- 1. parse + authenticate the caller (JWT) */
function parseRequest({ route, headers = {}, body = {} }, { jwtSecret, nowMs = Date.now() } = {}) {
  if (!ROUTES[route]) return fail('BAD_INPUT', 'unknown route');
  const h = Object.fromEntries(Object.keys(headers || {}).map((k) => [k.toLowerCase(), headers[k]]));
  const m = /^Bearer\s+(\S+)$/i.exec(String(h.authorization || ''));
  if (!m) return fail('AUTH', 'sign in again', {}, 401);
  let v;
  try { v = LT.verifySupabaseJwt(m[1], { secret: jwtSecret, nowMs }); } catch (e) { return fail('AUTH_NOT_CONFIGURED', 'SUPABASE_JWT_SECRET is not set'); }
  if (!v.ok) return fail('AUTH', 'sign in again', { reason: v.reason }, 401);
  const b = body && typeof body === 'object' ? body : {};
  const str = (x) => (typeof x === 'string' ? x.trim() : '');
  const out = { ok: true, route, user_id: v.user_id };
  if (b.confirmed_by && String(b.confirmed_by) !== v.user_id) return fail('NOT_ADMIN', 'confirmed_by must be the signed-in user', {}, 403);
  if (b.requested_by && String(b.requested_by) !== v.user_id) return fail('NOT_ADMIN', 'requested_by must be the signed-in user', {}, 403);
  if (route === 'confirm') {
    const action = str(b.action), target = str(b.target), reason = str(b.reason);
    if (!CONFIRM_ACTIONS.has(action)) return fail('UNSUPPORTED_ACTION', `ads-confirm handles ${[...CONFIRM_ACTIONS].join(', ')} here; other actions are setup tools`);
    if (!ID_RE.test(target)) return fail('BAD_INPUT', 'target (the Meta object id) is required');
    if (reason.length < 3) return fail('AUDIT_WHY', 'reason (why) is required, min 3 characters');
    if (!b.params || typeof b.params !== 'object' || Array.isArray(b.params)) return fail('BAD_INPUT', 'params must be an object');
    return { ...out, target, input: { action, target, params: b.params, reason } };
  }
  const token = str(b.confirm_token);
  if (!token) return fail('CONFIRM_REQUIRED', 'confirm_token required (confirm-to-apply)');
  if (route === 'budget') {
    const target = str(b.campaign_id), daily = Number(b.daily_budget_zar);
    if (!ID_RE.test(target)) return fail('BAD_INPUT', 'campaign_id required');
    if (!Number.isFinite(daily) || daily <= 0) return fail('BUDGET_INVALID', 'daily_budget_zar must be > 0 (to stop spend, pause the campaign)');
    return { ...out, target, input: { action: 'set_campaign_budget', target, token, params: { dailyBudgetZar: daily, setSpendCap: b.set_spend_cap === true, goLive: b.go_live === true } } };
  }
  const status = str(b.status).toUpperCase();
  if (status !== 'PAUSED' && status !== 'ACTIVE') return fail('BAD_INPUT', 'status must be PAUSED or ACTIVE');
  const target = str(route === 'ad-status' ? b.ad_id : b.campaign_id);
  if (!ID_RE.test(target)) return fail('BAD_INPUT', route === 'ad-status' ? 'ad_id required' : 'campaign_id required');
  const kind = route === 'ad-status' ? 'ad' : 'campaign';
  return { ...out, target, input: { action: `${status === 'PAUSED' ? 'pause' : 'resume'}_${kind}`, target, token, params: { status } } };
}

/* ---------------------------------------------------------------- 2. database context (one row, see SQL.context) */
const SQL = {
  context: `WITH b AS (SELECT * FROM public.brands WHERE code = 'SMC' LIMIT 1),
o AS (SELECT ao.* FROM public.ad_objects ao JOIN b ON b.id = ao.brand_id WHERE ao.id = $2)
SELECT public.has_role($1::uuid, 'admin'::public.app_role) AS is_admin,
  (SELECT to_jsonb(x) FROM (SELECT id::text AS id, code, business_id, page_id, ig_user_id, ad_account_id, pixel_id, dataset_id FROM b) x) AS brand,
  (SELECT to_jsonb(x) FROM (SELECT id, level, campaign_id, adset_id, name, status, effective_status, daily_budget_zar::float8 AS daily_budget_zar,
                                   spend_cap_zar::float8 AS spend_cap_zar, last_budget_change_at FROM o) x) AS obj,
  COALESCE((SELECT jsonb_agg(jsonb_build_object('broker_id', c.broker_id::text, 'share', c.media_share_zar::float8, 'starts_at', c.starts_at))
              FROM public.cycles c JOIN b ON b.id = c.brand_id JOIN public.brokers br ON br.id = c.broker_id
             WHERE c.status IN ('active', 'extended') AND br.status = 'active'), '[]'::jsonb) AS shares,
  (SELECT p.plan FROM public.ads_launch_plan p JOIN b ON b.id = p.brand_id) AS plan,
  (SELECT min(c.starts_at) FROM public.cycles c JOIN b ON b.id = c.brand_id JOIN public.brokers br ON br.id = c.broker_id WHERE c.status IN ('active', 'extended') AND br.status = 'active') AS cycle_start,
  (SELECT min(COALESCE(c.extended_until, c.ends_at)) FROM public.cycles c JOIN b ON b.id = c.brand_id JOIN public.brokers br ON br.id = c.broker_id WHERE c.status IN ('active', 'extended') AND br.status = 'active') AS cycle_end,
  (SELECT min(m.date)::text FROM public.ad_metrics m JOIN o ON m.campaign_id = o.id WHERE m.spend_zar > 0) AS first_spend_date,
  COALESCE((SELECT sum(m.spend_zar)::float8 FROM public.ad_metrics m JOIN o ON m.campaign_id = o.id
             WHERE m.date >= COALESCE((SELECT min(c.starts_at) FROM public.cycles c JOIN b ON b.id = c.brand_id JOIN public.brokers br ON br.id = c.broker_id
                                        WHERE c.status IN ('active', 'extended') AND br.status = 'active'), '-infinity'::timestamptz)::date), 0) AS spend_to_date;`,
  claim: `INSERT INTO public.ads_write_log (nonce, brand_id, action, target, params, before, requested_by, confirmed_by, reason)
VALUES ($1, $2::uuid, $3, $4, $5::jsonb, $6::jsonb, $7::uuid, $8::uuid, $9)
ON CONFLICT (nonce) DO NOTHING
RETURNING id::text AS log_id;`,
  record: `WITH u AS (
  UPDATE public.ads_write_log SET status = $2, result = $3::jsonb, error_code = $4, error_message = $5 WHERE id = $1::uuid RETURNING id, target
), o AS (
  UPDATE public.ad_objects ao SET daily_budget_zar = COALESCE($6::numeric, ao.daily_budget_zar), spend_cap_zar = COALESCE($7::numeric, ao.spend_cap_zar),
         status = COALESCE($8, ao.status), last_budget_change_at = CASE WHEN $6::numeric IS NOT NULL THEN now() ELSE ao.last_budget_change_at END, updated_at = now()
    FROM u WHERE ao.id = u.target AND $2 = 'applied' RETURNING ao.id
), n AS (
  INSERT INTO ops.notifications (kind, recipient, channel, source, status, ref_table, ref_id, dedupe_key, what, body, payload)
  SELECT 'ads_audit', 'jonathan', 'console', 'ads_write', 'queued', 'ads_write_log', u.id::text, $9, $10, $11::jsonb, $11::jsonb
    FROM u WHERE $2 IN ('applied', 'dry_run') RETURNING id
)
SELECT (SELECT count(*) FROM u) AS logged, (SELECT count(*) FROM o) AS cache_updated;`,
};

/* ---------------------------------------------------------------- 3. plan the write (all guardrails, no network) */
const keyOf = (name) => (/^SMC_([A-Z])_/.exec(String(name || '')) || [])[1] || null;
const newest = (shares) => [...shares].sort((a, b) => String(b.starts_at || '').localeCompare(String(a.starts_at || '')))[0];
const mintClient = (env, extra = {}) => M.createClient({ confirmSecret: env.META_CONFIRM_SECRET, ...extra });

function planWrite({ input, user_id, ctx, env = {}, nowMs = Date.now() }) {
  if (!ctx || ctx.is_admin !== true) return fail('NOT_ADMIN', 'admin only', {}, 403);
  let assets;
  try { assets = M.requireSmcAssets(ctx.brand, ['adAccountId']); } catch (e) { return fromErr(e); }
  const { action, target } = input;
  const level = action.endsWith('_ad') ? 'ad' : 'campaign';
  const obj = ctx.obj;
  if (!obj || String(obj.id) !== String(target) || obj.level !== level) return fail('TARGET_NOT_FOUND', `${level} ${target} is not a SortMyCover ${level} in the ad cache (hourly sync); nothing was sent`);
  const shares = Array.isArray(ctx.shares) ? ctx.shares : [];
  const plan = {
    action, target, level, assets, before: null, reason: input.reason, caps: null,
    params: null, preview: { action, target, name: obj.name, status: obj.effective_status || obj.status || null },
  };
  if (level === 'ad' || action.endsWith('_campaign')) {
    const status = action.startsWith('pause') ? 'PAUSED' : 'ACTIVE';
    if (input.params && input.params.status && String(input.params.status).toUpperCase() !== status) return fail('CONFIRM_MISMATCH', 'status does not match the action');
    plan.params = { status };
    plan.before = { status: obj.status || null };
    plan.preview = { ...plan.preview, change: `${obj.status || '?'} -> ${status}` };
    if (action === 'resume_ad' && /^(DISAPPROVED|WITH_ISSUES)$/.test(String(obj.effective_status || ''))) return fail('BAD_TARGET', `Meta shows this ad as ${obj.effective_status}; fix and resubmit it first`);
    return { ok: true, plan };
  }
  // ---- set_campaign_budget
  const key = keyOf(obj.name);
  if (!key) return fail('BAD_TARGET', `campaign "${obj.name}" does not follow SMC_{key}_... naming`);
  const merged = LP.mergePlan(ctx.plan);
  const p = input.params || {};
  const daily = Number(p.dailyBudgetZar);
  const setSpendCap = p.setSpendCap === true;
  const goLive = p.goLive === true;
  let caps;
  try { caps = LP.capsFor({ plan: merged, key, activeSharesZar: shares.map((s) => Number(s.share) || 0) }); } catch (e) { return fromErr(e); }
  let goLiveShareZar;
  if (goLive) {
    if (key !== 'A') return fail('GO_LIVE_ONLY_A', 'go-live raises apply to Campaign A only');
    if (!shares.length) return fail('GO_LIVE_NO_ACTIVE_CYCLE', 'no active broker cycle: nothing to go live with');
    goLiveShareZar = Number(newest(shares).share); // from cycles, never from the browser
  }
  const params = { dailyBudgetZar: daily, setSpendCap, monthlyCapZar: caps.monthlyCapZar };
  if (goLive) { params.goLive = true; params.goLiveShareZar = goLiveShareZar; }
  const current = obj.daily_budget_zar == null ? null : Number(obj.daily_budget_zar);
  // Caps are per 30-day broker cycle: spend counts from the earliest active cycle start (SQL spend_to_date); days remaining run to that cycle's end.
  // No active cycle (warm-up Reach, or nothing live): spend counts from the campaign's first spend and the days left come from the plan duration.
  const dayMs = 86400000;
  let daysRemaining;
  if (ctx.cycle_end) daysRemaining = Math.max(1, Math.ceil((new Date(ctx.cycle_end).getTime() - nowMs) / dayMs));
  else if (key === 'W') {
    const dur = Number((merged.campaigns.find((c) => c.key === 'W') || {}).duration_days) || 7;
    const used = ctx.first_spend_date ? Math.floor((nowMs - new Date(`${ctx.first_spend_date}T00:00:00Z`).getTime()) / dayMs) : 0;
    daysRemaining = Math.max(1, dur - used);
  } else daysRemaining = 30;
  const guard = { dailyBudgetZar: daily, currentDailyBudgetZar: current == null ? undefined : current, caps, monthSpendToDateZar: Number(ctx.spend_to_date) || 0,
    daysRemaining, lastChangeAt: obj.last_budget_change_at || undefined, goLive, goLiveShareZar };
  let checked;
  try { checked = mintClient(env, { brand: ctx.brand, now: () => nowMs }).checkBudget(guard); } catch (e) { return fromErr(e); }
  plan.params = params;
  plan.guard = guard;
  plan.caps = caps;
  plan.before = { dailyBudgetZar: current };
  plan.campaignKey = key;
  plan.preview = { ...plan.preview, daily_budget_old_zar: current, daily_budget_new_zar: daily, change_pct: current > 0 ? +(((daily - current) / current) * 100).toFixed(1) : null,
    billed_incl_vat_per_day_zar: LP.r2(daily * (1 + LP.VAT_RATE)), daily_cap_zar: caps.dailyCapZar, cycle_cap_zar: caps.monthlyCapZar, cycle_spend_zar: Number(ctx.spend_to_date) || 0, cycle_ends_at: ctx.cycle_end || null, days_remaining: daysRemaining,
    projected_cycle_spend_zar: LP.r2(checked.projected), set_spend_cap: setSpendCap, go_live: goLive, go_live_share_zar: goLive ? goLiveShareZar : null };
  return { ok: true, plan };
}

/* ---------------------------------------------------------------- 4. decide: preview + mint, or verify + hand over to apply */
function decide({ parsed, ctx, env = {}, nowMs = Date.now(), blockedUntil = 0 }) {
  if (!parsed || parsed.ok !== true) return parsed || fail('BAD_INPUT', 'no request');
  const { route, input, user_id } = parsed;
  const pw = planWrite({ input, user_id, ctx, env, nowMs });
  if (!pw.ok) return pw;
  const plan = pw.plan;
  if (blockedUntil && blockedUntil > nowMs) return fail('RATE_LIMIT_BACKOFF', 'Meta is busy', { retry_after_ms: blockedUntil - nowMs });
  let client;
  try { client = mintClient(env, { brand: ctx.brand, now: () => nowMs }); } catch (e) { return fromErr(e); }
  if (route === 'confirm') {
    try {
      const r = client.requestConfirm({ action: plan.action, target: plan.target, params: plan.params, requestedBy: user_id, reason: input.reason });
      return { ok: true, mode: 'respond', status: 200, body: { ok: true, confirm_token: r.confirmToken, expires_at: r.expiresAt, preview: plan.preview } };
    } catch (e) { return fromErr(e); }
  }
  // apply route: the token must have been minted for exactly these server-normalised params
  let d;
  try { d = client.verifyConfirm(input.token, { action: plan.action, target: plan.target, params: plan.params, confirmedBy: user_id }); } catch (e) { return fromErr(e); }
  return { ok: true, mode: 'apply', nonce: d.n, plan: { ...plan, reason: d.why, requestedBy: d.by }, confirmToken: input.token, confirmedBy: user_id, brandId: ctx.brand.id, brand: ctx.brand };
}

/* ---------------------------------------------------------------- 5. apply at Meta (the only network function) */
async function applyWrite({ d, env = {}, fetchImpl, nowMs, sleep }) {
  const plan = d.plan;
  const dry = String(env.ADS_DRY_RUN || '').toLowerCase() === 'true';
  if (dry) {
    // Rehearsal: the token and every guardrail were already checked in decide(); send nothing. Audit rows are still produced.
    return { ok: true, dry_run: true, result: { dry_run: true }, audit: dryAudit(d, nowMs), blockedUntil: 0 };
  }
  const client = M.createClient({ token: env.META_SYSTEM_USER_TOKEN, apiVersion: env.META_API_VERSION || undefined, confirmSecret: env.META_CONFIRM_SECRET, brand: d.brand,
    fetchImpl, sleep, now: nowMs ? () => nowMs : undefined, maxInlineWaitMs: 15000, maxRetries: 2 });
  const base = { confirmToken: d.confirmToken, confirmedBy: d.confirmedBy };
  try {
    let r;
    if (plan.action === 'set_campaign_budget') {
      const g = plan.guard;
      r = await client.setCampaignBudget({ campaignId: plan.target, dailyBudgetZar: plan.params.dailyBudgetZar, setSpendCap: plan.params.setSpendCap, caps: plan.caps,
        currentDailyBudgetZar: g.currentDailyBudgetZar, monthSpendToDateZar: g.monthSpendToDateZar, daysRemaining: g.daysRemaining, lastChangeAt: g.lastChangeAt,
        goLive: g.goLive, goLiveShareZar: g.goLive ? g.goLiveShareZar : undefined, ...base });
    } else if (plan.action === 'pause_ad') r = await client.pauseAd({ adId: plan.target, ...base });
    else if (plan.action === 'resume_ad') r = await client.resumeAd({ adId: plan.target, ...base });
    else if (plan.action === 'pause_campaign') r = await client.pauseCampaign({ campaignId: plan.target, ...base });
    else if (plan.action === 'resume_campaign') r = await client.resumeCampaign({ campaignId: plan.target, ...base });
    else return { ok: false, error: { code: 'UNSUPPORTED_ACTION', message: plan.action } };
    return { ok: true, result: r.result, audit: r.audit, notifications: r.notifications, blockedUntil: client.state.blockedUntil || 0, usagePct: client.state.lastUsage && client.state.lastUsage.pct };
  } catch (e) {
    return { ok: false, error: { code: e.code || 'API_ERROR', message: e.message, retry_after_ms: e.retryAfterMs, status: e.status, fbtrace_id: e.fbtrace_id }, blockedUntil: client.state.blockedUntil || 0 };
  }
}
function dryAudit(d, nowMs) {
  const at = new Date(nowMs || Date.now()).toISOString();
  return [{ at, actor_uid: d.confirmedBy, actor_role: 'admin', source: 'ads-api', table_name: 'meta_ads', row_id: String(d.plan.target), action: d.plan.action,
    diff: { before: d.plan.before, after: d.plan.params }, reason: d.plan.reason, requested_by: d.plan.requestedBy, dry_run: true }];
}

/* ---------------------------------------------------------------- 6. shape the response and the DB record */
function shape({ d, applied, nowMs = Date.now() }) {
  const plan = d.plan;
  const ok = applied.ok === true;
  const status = ok ? (applied.dry_run ? 'dry_run' : 'applied') : 'failed';
  const body = ok ? { ok: true, dry_run: !!applied.dry_run, action: plan.action, target: plan.target, audit: applied.audit } : { ok: false, code: applied.error.code, message: applied.error.message, ...(applied.error.retry_after_ms ? { retry_after_ms: applied.error.retry_after_ms } : {}) };
  const isBudget = plan.action === 'set_campaign_budget';
  const cacheDaily = ok && !applied.dry_run && isBudget ? plan.params.dailyBudgetZar : null;
  const cacheCap = ok && !applied.dry_run && isBudget && plan.params.setSpendCap ? plan.params.monthlyCapZar : null;
  const cacheStatus = ok && !applied.dry_run && !isBudget ? plan.params.status : null;
  const at = new Date(nowMs).toISOString();
  const note = { action: plan.action, target: plan.target, by: d.confirmedBy, requested_by: plan.requestedBy, why: plan.reason, before: plan.before, after: plan.params, dry_run: !!applied.dry_run, at };
  return {
    status: ok ? 200 : (STATUS_FOR[applied.error.code] || 502), body,
    record: [d.logId, status, JSON.stringify({ ok, audit: applied.audit || null, error: ok ? null : applied.error }), ok ? null : applied.error.code, ok ? null : String(applied.error.message || '').slice(0, 500),
      cacheDaily, cacheCap, cacheStatus, `ads_write:${plan.action}:${plan.target}:${d.nonce}`, `${plan.action} ${plan.target}: ${plan.reason}`.slice(0, 280), JSON.stringify(note)],
    blockedUntil: applied.blockedUntil || 0,
  };
}
const claimParams = (d) => [d.nonce, d.brandId, d.plan.action, d.plan.target, JSON.stringify(d.plan.params), JSON.stringify(d.plan.before), d.plan.requestedBy, d.confirmedBy, d.plan.reason];

module.exports = { ROUTES, SQL, parseRequest, planWrite, decide, applyWrite, shape, claimParams, fail, STATUS_FOR, keyOf };
