// W32 console approvals (I-30j / I-34d). Offline, zero dependencies: node --test automation/tests/W32.test.mjs
// Checks the 1-minute poll of ops.notifications in the exported automation/W32.json: the claim and ack SQL shape,
// the wiring into the existing decision branch, and runs the Code nodes in a vm sandbox (as W14.test.mjs does).
// W32.json is generated by optimisation/build-workflows.cjs; edit the generator, never the JSON.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const here = dirname(fileURLToPath(import.meta.url));
const WF = JSON.parse(readFileSync(join(here, '..', 'W32.json'), 'utf8'));
const MIG = join(here, '..', '..', 'supabase', 'migrations');
const node = (name) => { const n = WF.nodes.find((x) => x.name === name); assert.ok(n, `node ${name} exists`); return n; };
const outs = (name, idx = 0) => ((WF.connections[name] || { main: [] }).main[idx] || []).map((c) => c.node);
const sql = (name) => node(name).parameters.query.replace(/\s+/g, ' ').trim();

function runCode(name, input) {
  const wrap = (arr) => ({ all: () => arr.map((j) => ({ json: j })), first: () => ({ json: arr[0] }) });
  const ctx = vm.createContext({ $input: wrap(input), $env: {} });
  const out = vm.runInContext(`(function () {\n${node(name).parameters.jsCode}\n})()`, ctx);
  return JSON.parse(JSON.stringify(out.map((i) => i.json)));
}
const PID = '11111111-2222-4333-8444-555555555555';
const NID = 'aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee';
const row = (payload, extra = {}) => ({ id: NID, proposal_id: PID, payload, ...extra });

// ---------------------------------------------------------------- the poll
test('W32: a 1-minute Schedule Trigger polls console approvals (no Postgres LISTEN trigger)', () => {
  const t = node('Every minute: console approvals');
  assert.equal(t.type, 'n8n-nodes-base.scheduleTrigger');
  assert.equal(t.parameters.rule.interval[0].expression, '* * * * *');
  assert.ok(!WF.nodes.some((n) => n.type === 'n8n-nodes-base.postgresTrigger'), 'LISTEN drops events across restarts');
  assert.deepEqual(outs('Every minute: console approvals'), ['Claim console approvals']);
  assert.equal(WF.active, false, 'exported inactive');
});

test('W32: claim is one UPDATE ... FOR UPDATE SKIP LOCKED on kind approval, source console, status queued, returning the rows', () => {
  const q = sql('Claim console approvals');
  assert.match(q, /^UPDATE ops\.notifications n SET status = 'sending', updated_at = now\(\)/);
  assert.match(q, /WHERE n\.id IN \(SELECT id FROM ops\.notifications WHERE kind = 'approval' AND source = 'console' AND status = 'queued'/);
  assert.match(q, /ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT \d+\)/);
  assert.match(q, /RETURNING n\.id, n\.proposal_id, n\.payload;$/);
  assert.doesNotMatch(q, /source IS NULL|source = 'W32'/i, 'W32 own approval reminders are never consumed');
  assert.ok(!node('Claim console approvals').executeOnce, 'every claimed row flows on');
  // the claim is the only reader: no other W32 node selects queued console approvals without locking
  for (const n of WF.nodes.filter((x) => x.parameters && typeof x.parameters.query === 'string' && x.name !== 'Claim console approvals'))
    assert.doesNotMatch(n.parameters.query, /source = 'console'/, `${n.name} must not read console rows`);
});

test('W32: ack sets acked (acked_at, acked_by w32); failure sets send_failed with the error; both guarded on status sending', () => {
  const a = sql('Ack console approval');
  assert.match(a, /^UPDATE ops\.notifications SET status = 'acked', acked_at = now\(\), acked_by = 'w32', updated_at = now\(\) WHERE id = \$1::uuid AND status = 'sending'/);
  const f = sql('Mark console approval send_failed');
  assert.match(f, /^UPDATE ops\.notifications SET status = 'send_failed', error = \$2, updated_at = now\(\) WHERE id = \$1::uuid AND status = 'sending'/);
  assert.match(node('Ack console approval').parameters.options.queryReplacement, /\$\('Loop console approvals'\)\.first\(\)\.json\.id/);
  assert.match(node('Mark console approval send_failed').parameters.options.queryReplacement, /\$\('Loop console approvals'\)\.first\(\)\.json\.id/);
  for (const n of ['Ack console approval', 'Mark console approval send_failed']) assert.equal(node(n).alwaysOutputData, true, `${n} keeps the loop going`);
});

test('W32: every column and status value the poll writes exists in the migrations', () => {
  const all = readdirSync(MIG).filter((f) => f.endsWith('.sql')).map((f) => readFileSync(join(MIG, f), 'utf8')).join('\n');
  for (const c of ['status', 'updated_at', 'acked_at', 'acked_by', 'error', 'source', 'payload', 'proposal_id', 'kind', 'created_at'])
    assert.match(all, new RegExp(`\\b${c}\\b`), `ops.notifications.${c}`);
  const check = all.match(/status\s+IN \(([^)]*'send_failed'[^)]*)\)/);
  assert.ok(check, 'status check constraint found');
  for (const s of ['queued', 'sending', 'acked', 'send_failed']) assert.match(check[1], new RegExp(`'${s}'`), `status '${s}' allowed`);
});

// ---------------------------------------------------------------- routing
test('W32: loop routes each claimed row into the existing decision branch, then ack or send_failed, then back to the loop', () => {
  assert.deepEqual(outs('Claim console approvals'), ['Loop console approvals']);
  const loop = node('Loop console approvals');
  assert.equal(loop.type, 'n8n-nodes-base.splitInBatches'); assert.equal(loop.parameters.batchSize, 1);
  assert.deepEqual(outs('Loop console approvals', 1), ['Console row to decision'], 'loop output feeds one row at a time');
  assert.deepEqual(outs('Console row to decision'), ['Console row valid?']);
  assert.deepEqual(outs('Console row valid?', 0), ['Run decision branch (sub-call)']);
  assert.deepEqual(outs('Console row valid?', 1), ['Mark console approval send_failed']);
  const run = node('Run decision branch (sub-call)');
  assert.equal(run.type, 'n8n-nodes-base.executeWorkflow');
  assert.equal(run.parameters.workflowId.value, '={{ $workflow.id }}', 'calls this same workflow');
  assert.equal(run.parameters.options.waitForSubWorkflow, true);
  assert.equal(run.onError, 'continueErrorOutput'); assert.equal(run.alwaysOutputData, true);
  assert.deepEqual(outs('Run decision branch (sub-call)', 0), ['Ack console approval']);
  assert.deepEqual(outs('Run decision branch (sub-call)', 1), ['Mark console approval send_failed']);
  assert.deepEqual(outs('Ack console approval'), ['Loop console approvals']);
  assert.deepEqual(outs('Mark console approval send_failed'), ['Loop console approvals']);
  // the sub-call enters the same branch the webhook uses
  assert.equal(node('Console decision (sub-call)').type, 'n8n-nodes-base.executeWorkflowTrigger');
  assert.deepEqual(outs('Console decision (sub-call)'), ['Validate decision']);
  assert.deepEqual(outs('Approve decision'), ['Validate decision']);
});

test('W32: smc-w32-decision webhook stays, for the WhatsApp Approve button only', () => {
  const h = node('Approve decision');
  assert.equal(h.type, 'n8n-nodes-base.webhook'); assert.equal(h.parameters.path, 'smc-w32-decision');
  assert.equal(h.parameters.authentication, 'headerAuth');
  assert.match(node('Note').parameters.content, /WhatsApp button/);
  assert.match(node('Note').parameters.content, /I-34d/);
});

test('Console row to decision: approve, snooze and decline map to the body Validate decision reads; bad rows are rejected', () => {
  const ok = runCode('Console row to decision', [
    row({ decision: 'approve', proposal_id: PID, decided_by: 'u', reason: null, via: 'console' }),
    row({ decision: 'snooze', proposal_id: PID, via: 'console' }),
    row(JSON.stringify({ decision: 'decline', proposal_id: PID, reason: 'not now', via: 'console' })),
  ]);
  assert.deepEqual(ok.map((o) => o.valid), [true, true, true]);
  for (const o of ok) { assert.equal(o._via_console, true); assert.equal(o.notification_id, NID); assert.equal(o.body.proposal_id, PID); assert.equal(o.body.decided_by, 'console'); }
  assert.deepEqual(ok.map((o) => o.body.decision), ['approve', 'snooze', 'decline']);
  assert.equal(ok[2].body.reason, 'not now');
  const bad = runCode('Console row to decision', [
    row({ decision: 'later', proposal_id: PID }),
    row({ decision: 'approve' }, { proposal_id: null }),
    row({ decision: 'decline', proposal_id: PID, reason: '  ' }),
    row({ decision: 'approve', proposal_id: '99999999-2222-4333-8444-555555555555' }),
    row(null),
  ]);
  assert.deepEqual(bad.map((o) => o.valid), [false, false, false, false, false]);
  for (const o of bad) { assert.match(o.error, /^console approval: /); assert.equal(o._via_console, undefined); }
});

test('Validate decision: the sub-call item is via console; a webhook body cannot claim to be the console', () => {
  const [m] = runCode('Console row to decision', [row({ decision: 'approve', proposal_id: PID })]);
  const [v] = runCode('Validate decision', [m]);
  assert.deepEqual(v, { valid: true, decision: 'approve', proposal_id: PID, decided_by: 'console', reason: null, via: 'console' });
  const [w] = runCode('Validate decision', [{ headers: {}, body: { payload: `approve:${PID}`, from: '27600000000', _via_console: true } }]);
  assert.equal(w.valid, true); assert.equal(w.via, 'webhook'); assert.equal(w.decision, 'approve');
});

test('Decide: webhook path unchanged; console path only runs the follow-up once and never re-decides', () => {
  const d = node('Decide').parameters;
  const q = d.query.replace(/\s+/g, ' ');
  assert.match(d.options.queryReplacement, /\$\('Validate decision'\)\.first\(\)\.json\.via/);
  assert.match(q, /coalesce\(\$5::text, 'webhook'\) as via/);
  assert.match(q, /\(d\.via <> 'console' and p\.status in \('proposed', 'snoozed'\)\)/);
  assert.match(q, /d\.via = 'console' and p\.decided_by_label = 'console' and p\.task_id is null/);
  assert.match(q, /status = case when d\.via = 'console' then p\.status/);
  assert.match(q, /decided_at = case when d\.decision = 'later' or d\.via = 'console' then p\.decided_at/);
  assert.deepEqual(outs('Decide'), ['Ack action notifications']);
  assert.deepEqual(outs('Ack action notifications'), ['Approved?']);
});
