'use strict';
/* W25 renderers: every surface's numbers come from `pricing` rows passed in here (3.6).
 * Wording is creative-strategist's 3.5a rewrite (deliverables/creative-strategist/website-wording.md
 * section 2.3), which keeps 3.5a statements 1-7; contracts-drafter confirms the line under the cards. */
const { activeRows, cycleAmounts, derived } = require('./pricing');
const { formatZar } = require('./money');

const esc = (s) => String(s === null || s === undefined ? '' : s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

const TAGLINES = { SMC_BRONZE: 'Start here', SMC_SILVER: 'More volume', SMC_GOLD: 'Most volume' };

const LINE_UNDER_CARDS = 'Per 30-day cycle. No lock-in. Pay for a cycle, get your leads, decide again next cycle.';
const LINE_UNDER_CARDS_2 = 'Pay upfront by EFT or card; renew (or not) before your next cycle.';
const SMALL_PRINT = "Prices exclude VAT. No notice period: if you don't renew, the cycle simply ends.";

const statement4 = (cap) => `If a verified lead no-shows or can't be reached, we replace it — up to ${cap} per cycle on this plan. If we fall short of your committed number, your cycle extends by up to 14 days to deliver it, and anything still short is credited.`;
const statement7 = (n) => `${n} verified, pre-qualified leads per cycle — committed, not estimated. Short? We extend and credit.`;

/** Plain view-model per tier: what every surface may print. */
function tierView(row) {
  const a = cycleAmounts(row);
  return {
    tier_code: row.tier_code,
    name: row.name,
    tagline: row.tagline || TAGLINES[row.tier_code] || '',
    price: formatZar(a.excl_vat_cents),
    price_zar_display: formatZar(a.excl_vat_cents).replace(/^R/, ''),
    price_cents: a.excl_vat_cents,
    vat_line: a.vat_cents === null ? 'excl. VAT' : `plus VAT ${formatZar(a.vat_cents)} (total ${formatZar(a.total_cents)})`,
    total_cents: a.total_cents,
    committed_leads: row.committed_leads,
    replacement_cap_cycle: row.replacement_cap_cycle,
    per_lead: formatZar(derived(row).price_per_committed_lead_zar * 100),
  };
}

function renderTierCards(rows, { checkoutUrl = '/billing/checkout/', at, includeUnapproved = false } = {}) {
  const list = activeRows(rows, { at, includeUnapproved });
  const cards = list.map((r) => {
    const v = tierView(r);
    return `<article class="tier-card" data-tier="${esc(v.tier_code)}">
  <h3>${esc(v.name)}</h3><p class="tier-tagline">${esc(v.tagline)}</p>
  <p class="tier-price"><strong>${esc(v.price)}</strong> <span>/ 30-day cycle, ${esc(v.vat_line)}</span></p>
  <dl><dt>Pre-qualified leads</dt><dd>${esc(statement7(v.committed_leads))}</dd>
  <dt>Price per committed lead</dt><dd>${esc(v.per_lead)}</dd></dl>
  <ul>
    <li>${esc(v.committed_leads)} pre-qualified leads per cycle</li>
    <li>AI WhatsApp follow-up, booking &amp; reminders included</li>
    <li>Up to ${esc(v.replacement_cap_cycle)} replacements per cycle</li>
    <li>Media spend included</li>
    <li>Pre-call brief for every lead and a Monday report</li>
  </ul>
  <p class="tier-notes">${esc(statement4(v.replacement_cap_cycle))} Qualified means the 6 checks in our <a href="#what-qualified-means">definition</a>.</p>
  <a class="tier-cta" href="${esc(checkoutUrl)}?tier=${encodeURIComponent(v.tier_code)}">Start on ${esc(v.name)}</a>
</article>`;
  });
  return `<!-- GENERATED by W25 from the pricing table. Do not edit: change the pricing row instead. -->
<section class="tier-cards">
${cards.join('\n')}
</section>
<p class="under-cards"><strong>${esc(LINE_UNDER_CARDS)}</strong> ${esc(LINE_UNDER_CARDS_2)}</p>
<p class="small-print">${esc(SMALL_PRINT)}</p>`;
}

/** JSON the checkout page reads from data-pricing-json (only what the page needs). */
function checkoutPricingJson(rows, opts = {}) {
  return JSON.stringify(activeRows(rows, opts).map((r) => {
    const v = tierView(r);
    return { tier_code: v.tier_code, name: v.name, price_cents: v.price_cents, total_cents: v.total_cents, vat_line: v.vat_line,
      committed_leads: v.committed_leads, replacement_cap_cycle: v.replacement_cap_cycle, paystack_page_code: r.paystack_page_code || null, paystack_plan_code: r.paystack_plan_code || null };
  }));
}

/** {{key}} and {{key | default: "text"}} merge used by Schedule A, proposal and invoice templates. Unknown keys stay visible. */
function merge(template, vars) {
  return String(template).replace(/\{\{\s*([a-zA-Z0-9_]+)\s*(?:\|\s*default:\s*"([^"]*)")?\s*\}\}/g, (m, k, def) => {
    if (vars[k] !== undefined && vars[k] !== null && vars[k] !== '') return String(vars[k]);
    return def !== undefined ? def : m;
  });
}

/** Schedule A fields (deliverables/contracts-drafter/broker-services-agreement.md). */
function scheduleAVars(row, { payment_reference, exclusivity_terms } = {}) {
  const v = tierView(row);
  return { name: v.name, tier_code: v.tier_code, price_zar: v.price_zar_display, committed_leads: v.committed_leads, replacement_cap_cycle: v.replacement_cap_cycle,
    payment_reference: payment_reference || null, exclusivity_terms: exclusivity_terms || null };
}

/** Proposal tier block (3.6 consumer 3): tier, leads, replacements, price, what's included. */
function proposalTierBlock(row) {
  const v = tierView(row);
  return [
    `Plan: ${v.name} (${v.tier_code})`,
    `Price: ${v.price} per 30-day cycle, ${v.vat_line}. Paid in advance. Per 30-day cycle, no lock-in.`,
    `Committed: ${statement7(v.committed_leads)}`,
    `Replacements: up to ${v.replacement_cap_cycle} per cycle.`,
    'Included: ad spend, landing pages, WhatsApp assistant, booking, reminders, pre-call briefs, weekly reports. No setup fee. No per-policy fee.',
  ].join('\n');
}

/** Invoice template fields (3.6 consumer 5). */
function invoiceVars(invoice, row) {
  const v = tierView(row);
  return { invoice_no: invoice.invoice_no || '', plan: `${v.name} (${v.tier_code})`, period: invoice.period, reference: invoice.reference,
    amount_excl_vat: formatZar(Math.round(invoice.amount_excl_vat * 100), { decimals: true }),
    credit: invoice.credit_cents ? formatZar(-invoice.credit_cents, { decimals: true }) : '',
    vat: invoice.vat_zar === null ? 'Not VAT-registered: no VAT charged' : formatZar(Math.round(invoice.vat_zar * 100), { decimals: true }),
    total: formatZar(invoice.total_cents, { decimals: true }), due: invoice.due_at ? invoice.due_at.slice(0, 10) : '' };
}

module.exports = { tierView, renderTierCards, checkoutPricingJson, merge, scheduleAVars, proposalTierBlock, invoiceVars, LINE_UNDER_CARDS, LINE_UNDER_CARDS_2, SMALL_PRINT };
