-- UNDO of 20261010230000_smc_23_budget_three_bands.sql
-- Generated 2026-10-10 from a local catalog diff (supabase/drift/gen-undo.mjs). Run ONLY after every later migration's undo has run (reverse order).
-- Safe while no SortMyCover data exists. Dropping tables/columns here deletes whatever was written into them since the apply: take the backup first.
-- Review before running. Run in one transaction.
BEGIN;
SET LOCAL check_function_bodies = off;   -- restored function bodies may reference objects an earlier undo already dropped
ALTER TABLE "public"."leads" DROP CONSTRAINT IF EXISTS "leads_smc_checks";
ALTER TABLE "public"."leads" ADD CONSTRAINT "leads_smc_checks" CHECK ((((origin IS NULL) OR (origin = ANY (ARRAY['page'::text, 'lead_ad'::text, 'ctwa'::text, 'comment'::text, 'dm'::text, 'manual'::text]))) AND ((consent_mode IS NULL) OR (consent_mode = ANY (ARRAY['named'::text, 'generic'::text]))) AND ((line_type IS NULL) OR (line_type = ANY (ARRAY['mobile'::text, 'landline'::text, 'voip'::text, 'unknown'::text]))) AND ((call_number_line_type IS NULL) OR (call_number_line_type = ANY (ARRAY['mobile'::text, 'landline'::text, 'voip'::text, 'unknown'::text]))) AND ((age_band IS NULL) OR (age_band = ANY (ARRAY['lt35'::text, '35_44'::text, '45_50'::text, '51plus'::text]))) AND ((budget_band IS NULL) OR (budget_band = ANY (ARRAY['lt750'::text, '750_1250'::text, '1250plus'::text, '1250_1499'::text, '1500_plus'::text]))) AND ((method_pref IS NULL) OR (method_pref = ANY (ARRAY['teams'::text, 'zoom'::text, 'meet'::text, 'whatsapp_call'::text, 'phone'::text]))) AND ((alt_purpose IS NULL) OR (alt_purpose = 'reach_fallback'::text)) AND ((best_time IS NULL) OR (best_time = ANY (ARRAY['mornings'::text, 'lunchtime'::text, 'afternoons'::text, 'evenings'::text, 'any'::text]))) AND ((email_status IS NULL) OR (email_status = ANY (ARRAY['unchecked'::text, 'mx_ok'::text, 'delivered'::text, 'bounced'::text, 'corrected'::text]))) AND ((email_purpose IS NULL) OR (email_purpose = 'meeting_invite'::text)) AND ((stage IS NULL) OR (stage = ANY (ARRAY['new'::text, 'disclosed'::text, 'verified'::text, 'qualified'::text, 'booked'::text, 'confirmed'::text, 'attended'::text, 'no_show'::text, 'dispositioned'::text, 'unbooked_closed'::text, 'opted_out'::text, 'replacement_due'::text, 'disqualified'::text]))) AND ((brand_id IS NULL) OR (first_message_at IS NULL) OR (broker_id IS NOT NULL)) AND ((brand_id IS NULL) OR ((consent_at IS NOT NULL) AND (consent_text IS NOT NULL) AND (consent_source IS NOT NULL)))));  -- previous definition
COMMIT;
