#!/usr/bin/env python3
"""Generates analytics/tests/synthetic-seed.sql from analytics/tests/synthetic-cycle.json (edit the generator or the json, never the SQL).
One fictional Bronze adviser, one 30-day cycle, 5 ads at R350 a day, 30 sign-ups, 12 bookings, 10 outcomes, written into the REAL operational tables
(smc_02/03) so the real facts views read them. Every row is_synthetic = true; names say Synthetic, phones are +27 60 000 xxxx, emails are example.com.
All dates are shifted so the data ends TODAY (SA date): the old design's 2026-10-18 becomes facts.sa_date(now()); no facts.as_of needed.
Run after the smc migrations on a scratch database with:  SET smc.allow_synthetic = 'on';  (the file refuses otherwise).
Usage: python3 gen-synthetic-seed.py > synthetic-seed.sql"""
import json, os, collections
d = json.load(open(os.path.join(os.path.dirname(__file__), 'synthetic-cycle.json')))
BRK, USR, CYC = '00000000-0000-4000-8000-0000000b0002', '00000000-0000-4000-8000-00000000b002', '00000000-0000-4000-8000-0000000c0002'
def lid(k): return '00000000-0000-4000-8000-0000000a%04d' % int(k[1:])
def bid(k): return '00000000-0000-4000-8000-0000000d%04d' % int(k[2:])
def oid(k): return '00000000-0000-4000-8000-0000000e%04d' % int(k[1:])
def ts(v): return "pg_temp.sh('%s')" % v if v else 'NULL'
def q(v): return 'NULL' if v is None else "'" + str(v).replace("'", "''") + "'"
ANGLE_AD = {'A1': ('bond', 'SMC-A1 Bond', 100), 'A2': ('work_cover', 'SMC-A2 Work cover', 80), 'A3': ('family', 'SMC-A3 Family', 70), 'A4': ('bond_b', 'SMC-A4 Bond (b)', 50), 'A5': ('income', 'SMC-A5 Income', 50)}
o = []
w = o.append
w("""-- analytics/tests/synthetic-seed.sql — GENERATED by gen-synthetic-seed.py. SYNTHETIC DATA ONLY. Do not edit; edit the generator.
-- Fictional adviser (Bronze, committed 20; cycles.replacement_cap is carried as data only), cycle of 30 days ending in 16 days, 5 ads at R350 a day, 30 sign-ups, 12 bookings, 10 outcomes.
-- Writes the real operational tables; read through facts.* (smc_04). Needs: SET smc.allow_synthetic = 'on'; and the smc migrations. Never run on production.
begin;
do $$ begin
  if coalesce(current_setting('smc.allow_synthetic', true), '') <> 'on' then
    raise exception 'synthetic-seed.sql: refusing to run. SET smc.allow_synthetic = ''on'' first (never on production).';
  end if;
end $$;
select set_config('smc.source', 'seed', true), set_config('smc.reason', 'analytics synthetic cycle', true);
create function pg_temp.sh(t text) returns timestamptz language sql as $f$ select t::timestamptz + (facts.sa_date(now()) - date '2026-10-18') * interval '1 day' $f$;
insert into auth.users (id, aud, role, email, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
values ('%s', 'authenticated', 'authenticated', 'synthetic.analytics@example.com', '{"provider":"email"}', '{"synthetic":true}', now(), now()) on conflict (id) do nothing;
insert into public.user_roles (user_id, role) values ('%s', 'broker') on conflict (user_id, role) do nothing;
insert into public.brokers (id, user_id, firm_name, contact_person, email, whatsapp_number, phone_number, status, brand_id, tier_code, ref_code, fsp_number, fsp_verified_at,
   calendar_provider, methods_supported, max_meetings_per_day, max_meetings_per_week, routing_on, consent_mode, languages, onboarding_step, approved_live_at, status_changed_at, close_rate)
select '%s', '%s', 'Synthetic Analytics Advisory (TEST ONLY)', 'Mark Synthetic', 'synthetic.analytics@example.com', '+27600009998', '+27600009998', 'active', b.id, 'SMC_BRONZE', 'TST02', 'TEST-00002', now() - interval '20 days',
   'outlook', array['teams','phone','whatsapp_call'], 3, 12, true, 'named', array['en'], 'done', now() - interval '15 days', now() - interval '15 days', 0.30
from public.brands b where b.code = 'SMC' on conflict (id) do nothing;
insert into public.cycles (id, broker_id, brand_id, tier_code, cycle_no, price_zar, committed_leads, replacement_cap, media_share_zar, starts_at, ends_at, status)
select '%s', '%s', b.id, p.tier_code, 1, p.price_zar, p.committed_leads, p.replacement_cap_cycle, p.media_share_zar,
       (facts.sa_date(now()) - 13)::timestamp at time zone 'Africa/Johannesburg', ((facts.sa_date(now()) - 13) + 30)::timestamp at time zone 'Africa/Johannesburg', 'active'
from public.brands b join public.pricing p on p.tier_code = 'SMC_BRONZE' where b.code = 'SMC' on conflict (id) do nothing;
update public.brokers set current_cycle_id = '%s' where id = '%s' and current_cycle_id is null;""" % (USR, USR, BRK, USR, CYC, BRK, CYC, BRK))
# leads
w("insert into public.leads (id, brand_id, broker_id, tier_code, cycle_id, routed_at, first_name, last_name, phone, email, origin, campaign_id, adset_id, ad_id, concept, angle, placement,"
  " consent_text, consent_text_version, consent_mode, consent_at, consent_source, first_message_at, wa_delivered_at, verified_at, qualified_at, disqualified_reason, is_synthetic, created_at) values")
rows = []
for i, r in enumerate(d['leads']):
    k, _b, _br, _cy, created, origin, camp, ad, angle, consent, qual, dq, fc, fms, ver, repl, thumbs, adset, concept, placement = r
    rows.append("((select 'x')::text::uuid, 0)")  # placeholder never used
    rows[-1] = ("('%s', (select id from public.brands where code = 'SMC'), '%s', 'SMC_BRONZE', '%s', %s, 'Synthetic', 'Lead-%s', '+2760000%04d', 'synthetic.%s@example.com', %s, %s, %s, %s, %s, %s, %s,"
                " 'I agree that Lead Velocity may share my details with a named adviser. [SYNTHETIC]', 'named-v0-synthetic', 'named', %s, 'page', %s, %s, %s, %s, %s, true, %s)"
                % (lid(k), BRK, CYC, ts(created), k[1:], int(k[1:]), k.lower(), q(origin), q(camp), q(adset), q(ad), q(concept), q(angle), q(placement),
                   ts(created), ts(fc), "pg_temp.sh('%s')::timestamptz + interval '2 seconds'" % fc, ts(ver),
                   ("pg_temp.sh('%s') + interval '1 minute'" % created) if qual else 'NULL', q(dq), ts(created)))
w(',\n'.join(rows) + ';')
# bookings
w("insert into public.appointments (id, broker_id, client_id, appointment_date, ends_at, status, method, brand_id, cycle_id, booked_via, booked_at) values")
rows = []
for r in d['bookings']:
    k, lk, _b, _c, ad, angle, booked, slot, status, method = r
    rows.append("('%s', '%s', '%s', %s, %s + interval '30 minutes', '%s', '%s', (select id from public.brands where code = 'SMC'), '%s', 'page', %s)" % (bid(k), BRK, lid(lk), ts(slot), ts(slot), status, method, CYC, ts(booked)))
w(',\n'.join(rows) + ';')
# outcomes
w("insert into public.outcomes (id, booking_id, lead_id, broker_id, cycle_id, brand_id, outcome, disposition_code, quality_score, lead_reach_check, marked_via, marked_at, auto_marked, unconfirmed) values")
rows = []
for r in d['outcomes']:
    k, bk, lk, _b, _c, ad, angle, marked, outc, disp, qual, auto, unconf, reach = r
    rows.append("('%s', '%s', '%s', '%s', '%s', (select id from public.brands where code = 'SMC'), '%s', %s, %s, '%s', '%s', %s, %s, %s)" %
                (oid(k), bid(bk), lid(lk), BRK, CYC, outc, ("'%s'::public.smc_disposition_code" % disp) if disp else 'NULL', 'NULL' if qual is None else qual, reach,
                 'auto' if auto else 'whatsapp', ts(marked), 'true' if auto else 'false', 'true' if unconf else 'false'))
w(',\n'.join(rows) + ';')
# replacement (L08 no-show replaced), lead pulse, themes, report
w("insert into public.replacements (lead_id, cycle_id, broker_id, brand_id, reason, status, claimed_at) select '%s', '%s', '%s', b.id, 'no_show', 'approved', %s from public.brands b where b.code = 'SMC';" % (lid('L08'), CYC, BRK, ts('2026-10-11 09:00:00+00')))
pulse = [(r[0], r[16]) for r in d['leads'] if r[16] is not None]
w("insert into public.lead_pulse (lead_id, brand_id, broker_id, cycle_id, thumbs, answered_at) values")
w(',\n'.join("('%s', (select id from public.brands where code = 'SMC'), '%s', '%s', '%s', %s)" % (lid(k), BRK, CYC, 'up' if t == 1 else 'down', ts([r[4] for r in d['leads'] if r[0] == k][0])) for k, t in pulse) + ';')
themes = collections.Counter(t[3] for t in d['themes'])
TEXT = {'bond': 'Does this cover my bond?', 'dependants': 'What happens to my children if I die?', 'work_cover': 'Is my work cover enough?', 'premium_cost': 'How much will it cost each month?'}
w("insert into public.insights (brand_id, source, broker_id, cycle_id, kind, text, n) values")
w(',\n'.join("((select id from public.brands where code = 'SMC'), 'precall_question', '%s', '%s', 'theme', %s, %d)" % (BRK, CYC, q(TEXT.get(t, t)), n) for t, n in themes.items()) + ';')
w("insert into public.report_history (status, brand_id, broker_id, cycle_id, week, report_kind, sent_wa_at, opened_portal_at, ask) values ('sent', (select id from public.brands where code = 'SMC'), '%s', '%s', (%s)::date, 'broker_weekly', %s, %s, 'mark_outcomes');" % (BRK, CYC, "pg_temp.sh('2026-10-12 00:00:00+00')", ts('2026-10-12 05:00:00+00'), ts('2026-10-12 06:10:00+00')))
# ads and costs
leads_by = collections.Counter()
for r in d['leads']:
    leads_by[(r[4][:10], r[7])] += 1
days = sorted({r[4][:10] for r in d['leads']} | {'2026-10-%02d' % x for x in range(5, 19)})
w("insert into public.ad_metrics (date, brand_id, campaign_id, adset_id, ad_id, ad_name, concept, angle, placement, spend_zar, impressions, clicks, leads_raw, emq, frequency, hook_rate) values")
rows = []
for day in days:
    for ad, (ang, name, spend) in ANGLE_AD.items():
        rows.append("(pg_temp.sh('%s 12:00:00+00')::date, (select id from public.brands where code = 'SMC'), 'CMP-A', 'AS-1', '%s', '%s', '%s', '%s', 'feed', %d, %d, %d, %d, 7.2, 1.4, 0.28)" % (day, ad, name, ang, ang, spend, spend * 45, spend // 4, leads_by[(day, ad)]))
w(',\n'.join(rows) + ';')
perday = collections.Counter(r[4][:10] for r in d['leads'])
w("insert into ops.costs (date, kind, brand_id, broker_id, cycle_id, amount_zar, source_ref) values")
rows = []
for day, n in sorted(perday.items()):
    rows.append("(pg_temp.sh('%s 12:00:00+00')::date, 'whatsapp', (select id from public.brands where code = 'SMC'), '%s', '%s', %d, 'syn-wa-%s')" % (day, BRK, CYC, 2 * n, day))
    rows.append("(pg_temp.sh('%s 12:00:00+00')::date, 'llm', (select id from public.brands where code = 'SMC'), '%s', '%s', %d, 'syn-llm-%s')" % (day, BRK, CYC, n, day))
rows.append("(pg_temp.sh('2026-10-05 12:00:00+00')::date, 'infra', (select id from public.brands where code = 'SMC'), '%s', '%s', 450, 'syn-infra')" % (BRK, CYC))
rows.append("(pg_temp.sh('2026-10-05 12:00:00+00')::date, 'fees', (select id from public.brands where code = 'SMC'), '%s', '%s', 250, 'syn-fees')" % (BRK, CYC))
w(',\n'.join(rows) + ';')
w('commit;')
print('\n'.join(o))
